Change to Qt 6
iwalton3/jellyfin-media-player pull request #599
Opened 2024-04-19 18:23 UTC by nvllsvm

The Qt 6 branch seems stable in my limited testing (Arch Linux). Not sure about other platforms.

I've created an AUR package for this branch and encourage others to do some testing as well before this gets merged. https://aur.archlinux.org/packages/jellyfin-media-player-qt6-git

2024-04-19 18:31 UTC, nvllsvm commented
I'm debating where a final Qt 5 release should be made before this gets merged. Mainly to bring in the mpv 0.38.0 compatibility fix.

@iwalton3 Thoughts?

2024-04-20 16:08 UTC, sevenrats commented
This branch is fully unsuitable for release, and releasing it would currently add no value to the ecosystem.  Qt6 does not give us *anything* in a world where 5.15.11 exists. The most reasonable way forward is to ride Qt5 until compat loses support. Within that time we should have built an OSC per #537  or the related Qt Bug will have been fixed.  Then we can port to the native API and at that point we can discuss sunsetting the Qt5 build.  Migrating now would be way beyond premature imho.

2024-04-20 16:15 UTC, iwalton3 commented
This needs to be held until we either:

- reach feature parity with the 5.x branch
- are forced to switch to it because the ecosystem around it breaks

Notably the rendering pipeline is completely busted and we're using a UI cutout workaround to make it even slightly work that kills all overlay menus and trick play in the player.

2024-04-20 16:15 UTC, iwalton3 requested changes
See comment.

2024-04-20 16:38 UTC, sevenrats commented
some of these other changes are very good @nvllsvm, do you intend to open a new pr with them?

2024-04-20 18:12 UTC, nvllsvm commented
@sevenrats Took a first pass and added a few of those changes to https://github.com/jellyfin/jellyfin-media-player/pull/603

2024-05-03 15:17 UTC, satmandu commented
Would you please add these ubuntu packages to the list of required packages for building for QT6 in Readme.md?
`qt6-5compat-dev qt6-base-dev qt6-base-private-devqt6-declarative-dev qt6-webchannel-dev qt6-webengine-dev`

2024-05-06 10:44 UTC, kenden commented
This would help with the message
```
Uses an end-of-life runtime
The runtime used by this app is no longer receiving security updates
```
from https://flathub.org/apps/com.github.iwalton3.jellyfin-media-player

2024-05-06 10:50 UTC, sevenrats commented
@kenden 
I suspect this has to do with the flatpak itself. Qt5 is not EoL for another 12 months, so, whatever runtime you have that is outdated is probably unrelated to this issue.

2024-05-06 11:41 UTC, kenden commented
Thanks @sevenrats I think this is actually described in this issue: https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/issues/41

2025-05-02 09:42 UTC, Pentaphon commented
> Qt5 is not EoL for another 12 months

We are now weeks away.

2025-08-28 01:23 UTC, huantianad commented
Hi, hate to be the "update pls" person, but any progress on this? This package is now marked as insecure on NixOS (see https://github.com/NixOS/nixpkgs/pull/435067) because of its dependency on qt5's qtwebengine.

2025-08-30 13:18 UTC, ItsLiyua commented
Is this still in development? I just tried downloading the media player from the nixpkgs repo only to find out it depends on qtwebengine-5 which is marked as "insecure" due to being unmaintained upstream.

2025-09-03 02:34 UTC, clhodapp commented
To give some color as to why `nixpkgs` blocklisted qwebengine5, their error message says:
```
qt5 qtwebengine is unmaintained upstream since april 2025.
It is based on chromium 87.0.4280.144, and supposedly patched up to 135.0.7049.95 which is outdated.

Security issues are frequently discovered in chromium.
The following list of CVEs was fixed in the life cycle of chromium 138 and likely also affects qtwebengine:
- CVE-2025-8879
- CVE-2025-8880
- CVE-2025-8901
- CVE-2025-8881
- CVE-2025-8882
- CVE-2025-8576
- CVE-2025-8577
- CVE-2025-8578
- CVE-2025-8579
- CVE-2025-8580
- CVE-2025-8581
- CVE-2025-8582
- CVE-2025-8583
- CVE-2025-8292
- CVE-2025-8010
- CVE-2025-8011
- CVE-2025-7656
- CVE-2025-6558 (known to be exploited in the wild)
- CVE-2025-7657
- CVE-2025-6554
- CVE-2025-6555
- CVE-2025-6556
- CVE-2025-6557

The actual list of CVEs affecting qtwebengine is likely much longer,
as this list is missing issues fixed in chromium 136/137 and even more
issues are continuously discovered and lack upstream fixes in qtwebengine.
```

So it sounds like the library is kind of bad news at this point. However, it's possible to work around the issue very easily by following some simple instructions that get spat out along with the error. It seems like the primary attack to be afraid of would be your Jellyfin server attacking your Jellyfin client, which doesn't seem all that scary to me if you control both.

That said, it does seem like "are forced to switch to it because the ecosystem around it breaks" is arguably here now (at least the beginning of that situation).

2025-09-03 08:39 UTC, ItsLiyua commented
I'm not really worried about Jellyfin attacking my device because as you said, I control both the server and the client. However it's not possible to only whitelist the qtwebengine package if it's a jellyfin dependency. So now more or less any service could have that as a dependency and I wouldn't know unless I check manually. If I were to download a webbrowser or whatever and qtwebengine is a dependency I might not know and expose a vulnerability.

And on other distros there might not even be a warning. They might just get the vulnerable dependency without knowing it's vulnerable. I can imagine someone setting up a fake "public" jellyfin server to attack people who google "Jellyfin test server" or whatever.

2025-09-14 13:23 UTC, GDBlaster commented
> Is this still in development? I just tried downloading the media player from the nixpkgs repo only to find out it depends on qtwebengine-5 which is marked as "insecure" due to being unmaintained upstream.

there are a lot of CVEs and I didnt check them all but if the only referrer of qt5-qtwebengine you have is JMP none of those are relevant since you are not accessing webpages that are potentially malicious unless it gets significantly worse you are still safe with this package on your system

2025-10-24 03:04 UTC, iwalton3 commented
Ahh yes the positioning workaround fix. I was never happy with it because it broke thumbnail previews and drop-down menus, hence I basically tabled this project and decided to wait until I was forced to revisit it due to Qt 5 being end of life.

I consider a proper fix to be fix rendering with upstream (unlikely) or implement a completely custom player UI.

The latter is a lot of work, and honestly may make sense to switch to a better technical baseline if we abandon the main reason we use the abomination of a rendering pipeline this uses as it would add things like proper HDR and Dolby vision support. (In other words, there's a reason the upstream Plex Media Player application passed it's sell by date and this is likely it.)

In this way MPV Shim always had a better technical foundation but the player UI leaves a lot to be desired for normal users. (I did add trick play to that though, proving you can paper over a lot of UX issues with it with enough LUA scripts though.)

2025-11-23 00:33 UTC, ItsLiyua commented
I've seen you working on this and I just wanna say thank you! Sadly I lack the skill to help. Thanks for doing this!

2025-11-23 01:58 UTC, andrewrabert commented
@iwalton3 This works fine on Arch Linux with the mpvqt package installed. Other platforms need fixes to get it building (eg. CI tests), but I'd like to commit any fixes to that after this PR gets merged.

Merging this would allow the Arch Linux AUR jellyfin-media-player-git package to build and be used with qt6.

I'm currently looking into the issues building on other platforms and will open PR's to fix those later.

2025-11-23 02:16 UTC, iwalton3 approved these changes

2025-11-23 02:16 UTC, iwalton3 commented on native/mpvVideoPlayer.js
> +            console.log('[MPV] setSecondarySubtitleStreamIndex not supported, ignoring index:', index);
It does seem to be supported: https://mpv.io/manual/master/#select-select-secondary-sid

2025-11-23 02:17 UTC, merged