Fix desktop icon
iwalton3/jellyfin-media-player pull request #771
Opened 2024-10-04 23:36 UTC by solidsnake1298

Fix desktop icon.  Currently when JMP is docked/favorited and then launched it will spawn a separate icon.  Setting the StartupWMClass to jellyfinmediaplayer resolves this.

Credit goes to this user on the forum.

https://forum.jellyfin.org/t-desktop-entry-icon-bug-on-linux-client

2024-10-04 23:50 UTC, M4dMikel commented
Thanks for helping out and also for the credits.

2025-01-17 08:00 UTC, bjornfor requested changes
Although this PR fixes the icon issue for me on NixOS with GNOME (Wayland) desktop, I don't necessarily think it alone is a proper fix. The reason is that my jellyfin-media-player instance uses xwayland, not native wayland!

To check yourself, list all xwayland clients:

```
$ xlsclients
bf-laptop  keepassxc
bf-laptop  gsd-xsettings
bf-laptop  jellyfinmediaplayer   <--- bug!
bf-laptop  mutter-x11-frames
```

So either we fix the packaging so that the app runs with native wayland protocol, or the fix must work for both X11 and Wayland. (Currently I think this PR only works for X11.)

2025-12-04 23:55 UTC, andrewrabert commented
Fwiw - a build of main works great on native wayland (Plasma 6). Not sure when a stable release will be made available though.

2025-12-04 23:56 UTC, closed without merging

2025-12-04 23:56 UTC, andrewrabert commented
Closed as it's not the correct solution. Happy to discuss further.